core:
  name: "Haven"
  modes: ""
  authors: ["GamerzKing"]
  type: "NORMAL"

locations:
  min:
    x: 1
    y: 1
    z: 1
  max:
    x: 1
    y: 1
    z: 1
  spectator: "0,64,0"
  spawns:
    - "0,64,0"
    - "0,64,0"
    - "0,64,0"
    - "0,64,0"
    - "0,64,0"
    - "0,64,0"
    - "0,64,0"