core:
  name: "Orbis Harbor"
  authors: ["GamerzKing"]
  type: "NORMAL"

locations:
  min:
    x: 1
    y: 1
    z: 1
  max:
    x: 1
    y: 1
    z: 1
  spectator: "0,0,0"
  spawns:
    - "0,0,0"
    - "0,0,0"
    - "0,0,0"
    - "0,0,0"
    - "0,0,0"
    - "0,0,0"
    - "0,0,0"
  chests:
    - "0,0,0"
    - "0,0,0"
    - "0,0,0"
    - "0,0,0"
    - "0,0,0"
    - "0,0,0"
    - "0,0,0"
    - "0,0,0"
    - "0,0,0"
    - "0,0,0"
    - "0,0,0"
    - "0,0,0"