main: dev.thomashanson.wizards.WizardsPlugin
name: Wizards
version: 1.4.0
api-version: 1.19

author: GamerzKing
depend:
  - FastAsyncWorldEdit
  - ProtocolLib
  - CommandAPI
description: The last wizard alive wins!